<?php
/**
 * @author VIJAYAKUMAR S
 * @copyright Copyright (c) 2018
 * @package Learn_Whatsappshare
 */
?>
<?php
$helper = $this->helperInit();

$objectManagerInstance = \Magento\Framework\App\ObjectManager::getInstance();
$url = $objectManagerInstance -> get('Magento\Framework\UrlInterface');
$currentUrl = $url -> getCurrentUrl();

$active = $helper->whatsappshare_enable();
$size = $helper->whatsappshare_size();
$text = $helper->whatsappshare_text();

$size_class = "whatsapp_small";
if($size == 1) {
	$size_class = "whatsapp_small";
} else if($size == 2) {
	$size_class = "whatsapp_medium";
} else if($size == 3) {
	$size_class = "whatsapp_large";
}



if($helper->isMobile() || $helper->isTablet()) {
	/* <a href="whatsapp://send?text=<?php echo $text?>%0A%0A<?php echo "",$currentUrl."%3Futm_source%3Dwhatsappshare";?>" class=""><?php echo __('Share');?></a> */
	?>
	<div class="whatsapp_share <?php echo $size_class; ?>">
		<a href="whatsapp://send?text=<?php echo $text?>%0A%0A<?php echo "",$currentUrl."";?>"><?php echo __('Share');?></a>
	</div>	
	<?php 
} else {
	?>
	<div class="whatsapp_share <?php echo $size_class; ?>">
		<a href="https://web.whatsapp.com/send?text=<?php echo $text?>%0A%0A<?php echo "",$currentUrl."";?>" target="_blank"><?php echo __('Share');?></a>
	</div>
	<?php
}
?>